export const CHECKOUT_SELECTORS = {
  FORM: ".checkout_info",
  FIRST_NAME_INPUT: "#first-name",
  LAST_NAME_INPUT: "#last-name",
  POSTAL_CODE_INPUT: "#postal-code",
  ERROR_MESSAGE: ".error-message-container",
  CANCEL_BUTTON: "#cancel",
  CONTINUE_BUTTON: "#continue",
  PAYMENT_INFO: '[data-test="payment-info-label"]',
  PAYMENT_VALUE: '[data-test="payment-info-value"]',
  SHIPPING_INFO: '[data-test="shipping-info-label"]',
  SHIPPING_VALUE: '[data-test="shipping-info-value"]',
  PRICE_INFO: '[data-test="total-info-label"]',
  PRICE_SUBTOTAL: ".summary_subtotal_label",
  PRICE_TAX: ".summary_tax_label",
  PRICE_TOTAL: ".summary_total_label",
  FINISH_BUTTON: "#finish",
  SUCCESS_IMAGE: ".pony_express",
  SUCCESS_TITLE: ".complete-header",
  SUCCESS_MESSAGE: ".complete-text",
  BACK_HOME_BUTTON: "#back-to-products",
} as const;
