name: 🎭 E2E Playwright Tests

on:
  workflow_dispatch:
    inputs:
      trigger_mode:
        description: "Select your trigger mode:"
        required: true
        type: choice
        options:
          - PRODUCTION
          - STAGING

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      BASE_URL: ${{ secrets.BASE_URL }}
      VALID_USER: ${{ secrets.VALID_USER }}
      LOCKED_USER: ${{ secrets.LOCKED_USER }}
      VALID_PASSWORD: ${{ secrets.VALID_PASSWORD }}

    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444
        with:
          node-version: lts/*

      - name: 📦 Install Dependencies
        run: npm ci

      - name: 🎭 Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: ▶️ Run Playwright Tests
        run: npx playwright test tests

      - name: 📤 Upload Test Report
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
